### ISSUE TITLE
miniViewer Unknown image type error when using drag & drop

### ISSUE THREAD

**Issue by iarata** [facebookresearch/chameleon#19]
When running the `python -m chameleon.miniviewer` command and trying to upload an image using the drag and drop, the `file_input.files[0]` object becomes null and the `user_inputs` for the image's value will be `undefined` causing the following error:
```python
Exception in thread Thread-1 (generation_thread):
Traceback (most recent call last):
  File "/home/arata/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/arata/.pyenv/versions/3.11.9/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/media/research/others/chameleon/chameleon/miniviewer/miniviewer.py", line 182, in generation_thread
    for token in model.stream(
  File "/media/research/others/chameleon/chameleon/inference/chameleon.py", line 625, in stream
    batch_input_ids = [
                      ^
  File "/media/research/others/chameleon/chameleon/inference/chameleon.py", line 626, in <listcomp>
    self.token_manager.tokens_from_ui(prompt_ui)
  File "/media/research/others/chameleon/chameleon/inference/chameleon.py", line 162, in tokens_from_ui
    raise ValueError("Unknown image type.")
ValueError: Unknown image type.
```

To reproduce:
- Run the `python -m chameleon.miniviewer` command
- Click on `Add image input` and drag and drop an image to the input area
- Click on `Generate`

Environment:
- OS: macOS Sonoma 14.5
- Browser: Arc 1.47.1
- Image formats tried: png, jpg, bmp

**Comment by lshamis** [comment]
Fix merged
