### ISSUE TITLE
subprocess.CalledProcessError: Command '['wget', '--continue', '[pre-signed URL]', '-O', 'data/tokenizer/text_tokenizer.json']' returned non-zero exit status 8.

### ISSUE THREAD

**Issue by jsm69** [facebookresearch/chameleon#29]
Hi, Why I'm getting this error when I download the model? Any fix? using the correct model URL given the the email. 

```
Resolving dbj4kdlgwwbrp.cloudfront.net (dbj4kdlgwwbrp.cloudfront.net)... 18.64.50.129, 18.64.50.121, 18.64.50.122, ...
Connecting to dbj4kdlgwwbrp.cloudfront.net (dbj4kdlgwwbrp.cloudfront.net)|18.64.50.129|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden.
2024-06-20 14:22:35 ERROR 403: Forbidden..

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/chameleon/download_data.py", line 88, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/chameleon/download_data.py", line 74, in main
    download_tokenizer(presigned_url, target_folder)
  File "/usr/local/lib/python3.11/site-packages/chameleon/download_data.py", line 35, in download_tokenizer
    download_file(
  File "/usr/local/lib/python3.11/site-packages/chameleon/download_data.py", line 12, in download_file
    subprocess.check_call(["wget", "--continue", url, "-O", str(output_path)])
  File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--continue', '[pre-signed URL]', '-O', 'data/tokenizer/text_tokenizer.json']' returned non-zero exit status 8.
```

**Comment by lshamis** [comment]
Try running `wget -d --continue [pre-signed URL] -O data/tokenizer/text_tokenizer.json`.
The `-d` flag will provide more information.

**Comment by jsm69** [comment]
Yes, This is the issue `<p>Excessive download attempts have been detected with this link. Please request a new <a href="https://ai.meta.com/llama/">download link</a> via the web form.</p>` 

Please fix this @lshamis

**Comment by lshamis** [comment]
There is a limit to the number of downloads per pre-signed URL. Please sign up again and get a new URL.

**Comment by jsm69** [comment]
> There is a limit to the number of downloads per pre-signed URL. Please sign up again and get a new URL.

It takes a lot of time to get a new URL from Meta. Why not remove this limit?

**Comment by tingxueronghua** [comment]
So we are not getting a unique url per request? Then what is the meaning of requesting the URL?
