### ISSUE TITLE
30B Model Single GPU Inference Code Request

### ISSUE THREAD

**Issue by dalan2014** [facebookresearch/chameleon#30]
## Description
I am trying to perform inference with the 30B model using the Chameleon library. By default, the 30B model is distributed across 4 GPUs, but I only have a single A100 80G available.

## Error
When trying to run the 30B model, I encounter the following error:
```
# python -m chameleon.miniviewer --model-size 30b
VQModel loaded from data/tokenizer/vqgan.ckpt
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/BD/chameleon/chameleon/inference/chameleon.py", line 492, in _worker_impl
    torch.cuda.set_device(rank)
  File "/data/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Process SpawnProcess-4:
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/BD/chameleon/chameleon/inference/chameleon.py", line 492, in _worker_impl
    torch.cuda.set_device(rank)
  File "/data/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Process SpawnProcess-5:
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/BD/chameleon/chameleon/inference/chameleon.py", line 492, in _worker_impl
    torch.cuda.set_device(rank)
  File "/data/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

## Request

Could you please provide guidance or an example of how to perform inference with the 30B model on a single A100 GPU using the Chameleon library?

Thank you!

**Comment by chiehpower** [comment]
I think you can check this [comment](https://github.com/facebookresearch/chameleon/issues/9#issuecomment-2177259271).

**Comment by lshamis** [comment]
The current implementation unfortunately requires a gpu per-shard. The HF release, which should be in a few day, will hopefully support one gpu. Another option is to try and consolidate the model into one shard, but we cannot provide guidance. Good luck.
