### ISSUE TITLE
NoneType error for inference and miniviewer

### ISSUE THREAD

**Issue by chihhuiho** [facebookresearch/chameleon#4]
Hi, 
Thanks for the great work. I run into the following error when running the multi-model inference example for the 7B model. The same error appears when lauching the miniviewer. The default config is used. Thanks in advance for the help.

Traceback (most recent call last):
 File "multimodal_input.py", line 6, in <module>
 from chameleon.inference.chameleon import ChameleonInferenceModel
 File "/home/ubuntu/johnho/chameleon/chameleon/inference/chameleon.py", line 31, in <module>
 from chameleon.inference import loader
 File "/home/ubuntu/johnho/chameleon/chameleon/inference/loader.py", line 13, in <module>
 from chameleon.inference.transformer import ModelArgs, Transformer
 File "/home/ubuntu/johnho/chameleon/chameleon/inference/transformer.py", line 19, in <module>
 class ModelArgs:
 File "/home/ubuntu/johnho/chameleon/chameleon/inference/transformer.py", line 24, in ModelArgs
 n_kv_heads: int | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by lshamis** [comment]
Type annotations like `int | None` are only supported in Python 3.10+
