### ISSUE TITLE
How to run th 7b model on CPU only?

### ISSUE THREAD

**Issue by 0wwafa** [facebookresearch/chameleon#5]
# python -m chameleon.miniviewer --model-size 7b
```
VQModel loaded from data/tokenizer/vqgan.ckpt
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/chameleon/chameleon/miniviewer/__main__.py", line 9, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/chameleon/chameleon/miniviewer/miniviewer.py", line 241, in main
    cm3v2_inference_model = ChameleonInferenceModel(
  File "/content/chameleon/chameleon/inference/chameleon.py", line 544, in __init__
    self.token_manager = TokenManager(
  File "/content/chameleon/chameleon/inference/chameleon.py", line 101, in __init__
    self.image_tokenizer = ImageTokenizer(
  File "/content/chameleon/chameleon/inference/image_tokenizer.py", line 38, in __init__
    self._vq_model.to(device)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Exception ignored in: <function ChameleonInferenceModel.__del__ at 0x7d4a1b10bd00>
Traceback (most recent call last):
  File "/content/chameleon/chameleon/inference/chameleon.py", line 572, in __del__
    with self.dctx.active_key_lock:
AttributeError: 'ChameleonInferenceModel' object has no attribute 'dctx'
```

**Comment by 0wwafa** [comment]
### Please add a cpu only example inference!

**Comment by lshamis** [comment]
cpu only is not supported at the moment. We may try to add it in the future, but we lean pretty hard on gpu-specific tricks (such as cuda-graphs) to be performant.

**Comment by jacobkahn** [comment]
HuggingFace will be the best way to accomplish this -- follow https://github.com/facebookresearch/chameleon/issues/3

**Comment by 0wwafa** [comment]
> cpu only is not supported at the moment. We may try to add it in the future, but we lean pretty hard on gpu-specific tricks (such as cuda-graphs) to be performant.

You should consider this. Since a 7B model usually is performant (3-7 tok/sec) on a cpu only setup.
I really wish to test the text-only capabilities.

**Comment by 0wwafa** [comment]
> HuggingFace will be the best way to accomplish this -- follow #3

no. I meant locally @jacobkahn

**Comment by jacobkahn** [comment]
@0wwafa HF [enables this](https://huggingface.co/docs/transformers/en/perf_infer_cpu)

**Comment by 0wwafa** [comment]
> @0wwafa HF [enables this](https://huggingface.co/docs/transformers/en/perf_infer_cpu)

yep. an example, or even better a colab notebook would be nice. since if it works on colab it can work anywhere...

**Comment by 0wwafa** [comment]
I still think you will miss big if you don't do this. I personally quantized in "my own way" a lot of models and they run all smoothly on cpu even without gpu.. 3-4 tokens/sec which is the speed at which most people read.
